from time import sleep
from PIL import Image

for i in range(10, -1, -1):
    if i <= 3:
        sleep(1)
    sleep(1)
    print(i)
sleep(0.5)
print("BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \nBBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \nBBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \nBBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \nBBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \nBBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   BBBBOOMMM   \n")
